export const name = 'wangyj-film-light'
export const base = 'vs-light'

export const colors = {
    primary: '#628969',
    foreground: '#0D0F10',
    background: '#D9D1BD',
    cursorColor: '#A6C1B7',
    selectionBackground: '#849e89',
    black: '#6D6D64',
    red: '#6D2E2E',
    yellow: '#7A4A26',
    green: '#3E8D6B',
    cyan: '#0F5E6D',
    blue: '#2A5273',
    purple: '#6A2D50',
    white: '#F5F2E8',
    brightBlack: '#181C1E',
    brightRed: '#6D2E2E',
    brightYellow: '#7A4A26',
    brightGreen: '#3E8D6B',
    brightCyan: '#0F5E6D',
    brightBlue: '#2A5273',
    brightPurple: '#6A2D50',
    brightWhite: '#707070',
}

export const tokenColors = {
    comment: '#4c6152',
    delimiters: '#55554a',
    constants: '#9d732b',
    entities: '#58994d',
    params: colors.brightWhite,
    tags: colors.brightGreen,
    keywords: colors.brightGreen,
    storage: colors.brightRed,
    htmlText: colors.brightWhite,
    strings: '#d1573e',
    support: '#847322',
    properties: '#847322',
    attributes: '#b2873d',
    variables: '#bc8340',
    types: colors.cyan,
    namespaces: colors.blue,
    operators: '#E28E6D',
    errors: colors.red,
    regex: '#E28E6D',
    regexSpecial: '#d1573e',
    regexEscape: '#c69f00',
    numbers: colors.brightBlue,
    units: colors.brightRed,
    booleans: colors.cyan,
    modules: colors.brightGreen,
    markdownList: '#e77423',
    headings: colors.brightGreen,
    quotes: colors.blue,
    links: colors.green,
    deleted: colors.brightRed,
    deletedBg: colors.red,
    inserted: colors.brightGreen,
    insertedBg: colors.green,
    changed: colors.brightYellow,
    changedBg: colors.yellow,
    ignored: '#363b40',
    ignoredBg: colors.brightBlue,
    diffRange: '#862fff',
    diffHeader: colors.brightBlue,
    brackets: colors.brightWhite,
    unmatchedBracket: colors.brightRed,
}
