export const name = 'wangyj-film-light'
export const base = 'vs-light'

export const colors = {
    primary: '#628969',
    foreground: '#0D0F10',
    background: '#D9D1BD',
    cursorColor: '#A6C1B7',
    selectionBackground: '#3A4A3D',
    black: '#6D6D64',
    red: '#E68E8E',
    yellow: '#E9B873',
    green: '#6BD4A2',
    cyan: '#5AC8DC',
    blue: '#7FB5E6',
    purple: '#D48FB8',
    white: '#F5F2E8',
    brightBlack: '#181C1E',
    brightRed: '#A05D5D',
    brightYellow: '#B07D52',
    brightGreen: '#3E8D6B',
    brightCyan: '#2F8E9E',
    brightBlue: '#4E7BA5',
    brightPurple: '#9A5A7A',
    brightWhite: '#A8A8A8',
}

export const tokenColors = {
    comment: '#6D8A75DD',
    delimiters: '#7A7A6ACC',
    constants: '#D4B682',
    entities: '#8FC286',
    params: colors.brightWhite,
    tags: colors.brightGreen,
    keywords: colors.brightGreen,
    storage: colors.brightRed,
    htmlText: colors.brightWhite,
    strings: '#e7a89b',
    support: '#e7d998',
    properties: '#e7d998',
    attributes: '#D4B682',
    variables: '#D9B78F',
    types: colors.cyan,
    namespaces: colors.blue,
    operators: '#E28E6D',
    errors: colors.red,
    regex: '#E28E6D',
    regexSpecial: '#e7a89b',
    regexEscape: '#FFEA95',
    numbers: colors.brightBlue,
    units: colors.brightRed,
    booleans: colors.cyan,
    modules: colors.brightGreen,
    markdownList: '#F2B58A',
    headings: colors.brightGreen,
    quotes: colors.blue,
    links: colors.green,
    deleted: colors.brightRed,
    deletedBg: colors.red,
    inserted: colors.brightGreen,
    insertedBg: colors.green,
    changed: colors.brightYellow,
    changedBg: colors.yellow,
    ignored: '#4D545B',
    ignoredBg: colors.brightBlue,
    diffRange: '#D1B0FF',
    diffHeader: colors.brightBlue,
    brackets: colors.brightWhite,
    unmatchedBracket: colors.brightRed,
}
