export const colors = {
    primary: '#628969',
    foreground: '#D9D1BD',
    background: '#0D0F10',
    cursorColor: '#A6C1B7',
    selectionBackground: '#3A4A3D',
    black: '#181C1E',
    red: '#A05D5D',
    yellow: '#B07D52',
    green: '#3E8D6B',
    cyan: '#2F8E9E',
    blue: '#4E7BA5',
    purple: '#9A5A7A',
    white: '#A8A8A8',
    brightBlack: '#6D6D64',
    brightRed: '#E68E8E',
    brightYellow: '#E9B873',
    brightGreen: '#6BD4A2',
    brightCyan: '#5AC8DC',
    brightBlue: '#7FB5E6',
    brightPurple: '#D48FB8',
    brightWhite: '#F5F2E8',
}

export const tokenColors = {
    comment: '#6D8A75DD',
    delimiters: '#7A7A6ACC',
    constants: '#D4B682',
    entities: '#8FC286',
    params: colors.brightWhite,
    tags: colors.brightGreen,
    keywords: colors.brightGreen,
    storage: colors.brightRed,
    htmlText: colors.brightWhite,
    strings: '#e7a89b',
    support: '#e7d998',
    properties: '#e7d998',
    attributes: '#D4B682',
    variables: '#D9B78F',
    types: colors.cyan,
    namespaces: colors.blue,
    operators: '#E28E6D',
    errors: colors.red,
    regex: '#E28E6D',
    regexSpecial: '#e7a89b',
    regexEscape: '#FFEA95',
    numbers: colors.brightBlue,
    units: colors.brightRed,
    booleans: colors.cyan,
    modules: colors.brightGreen,
    markdownList: '#F2B58A',
    headings: colors.brightGreen,
    quotes: colors.blue,
    links: colors.green,
    deleted: colors.brightRed,
    deletedBg: colors.red,
    inserted: colors.brightGreen,
    insertedBg: colors.green,
    changed: colors.brightYellow,
    changedBg: colors.yellow,
    ignored: '#4D545B',
    ignoredBg: colors.brightBlue,
    diffRange: '#D1B0FF',
    diffHeader: colors.brightBlue,
    brackets: colors.brightWhite,
    unmatchedBracket: colors.brightRed,
}

export const alpha = (color: string, alpha: string | number) => {
    return `${color}${alpha}`
}
